apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  namespace: kubeorion
spec:
  replicas: 1
  selector:
    matchLabels: { app: inventoryservice }
  template:
    metadata:
      labels: { app: inventoryservice }
    spec:
      # If you create a docker-registry secret (Option B below), uncomment:
      # imagePullSecrets:
      #   - name: acr-auth
      containers:
        - name: inventoryservice
          image: acrorionbusdemo.azurecr.io/inventoryservice:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          envFrom:
            - secretRef: { name: inventory-secrets }
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
  namespace: kubeorion
spec:
  type: ClusterIP
  selector: { app: inventoryservice }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
